spring:
  application:
    name: OutSpecs

  security:
    user:
      name: sa
      password: cc
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update     # 스키마 자동 생성/업데이트
    show-sql: true         # SQL 로그 출력
    properties:
      hibernate.format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.springframework.security.oauth2.client: TRACE
      org.springframework.security.oauth2.core: TRACE
      com.percent99.OutSpecs.security: DEBUG


aws:
  access-key-id: YOUR_ACCESS_KEY
  secret-access-key: YOUR_SECRET_KEY
  region: ap-northeast-2
  s3:
    bucket-name: my-java-app-files-2024

alan:
  BASE_URL: ${ALAN_BASE_URL}
  CLIENT_ID: ${ALAN_CLIENT_ID}